[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Security: Understanding the Risks and Opportunities Posed by Intelligent Technologies in Cyberspace"
